env: "local" # dev, prod
storage_path: "./storage/auth.db"
token_ttl: 1h
grpc:
  port: 44044
  timeout: 10h
database:
  host: localhost
  port: 5432
  user: pasha
  password: elena123
  dbname: auth
  sslmode: disable
